import { FinancialMetrics } from "@/types/financial";

export function parseFinancialData(
  text: string
): FinancialMetrics {
  const result: FinancialMetrics = {};

  // Robust Metadata Extraction
  // Look for "Exact name of registrant" or standard headers
  const companyMatch = text.match(/\(Exact name of registrant as specified in its charter\)\s*([^\n]+)/i) 
                    || text.match(/(?:Company Name|Registrant):\s*([^\n]+)/i);
  
  if (companyMatch) {
    result.company = companyMatch[1].trim();
  } else {
    // Fallback: look for lines ending in Inc., Corp., LLC, etc. near the top
    const topText = text.slice(0, 1000);
    const fallbackMatch = topText.match(/^([A-Z][a-zA-Z\s,&]+(?:Inc\.|Corporation|Corp\.|LLC|Ltd\.|Company))\s*$/m);
    if (fallbackMatch) {
      result.company = fallbackMatch[1].trim();
    } else {
      // Ultimate fallback: Just use "Unknown Company" instead of random PDF text
      result.company = "Unknown Company";
    }
  }

  const reportTypeMatch = text.match(/\b(FORM\s+10-[KQ])\b/i) || text.match(/\b(10-[KQ])\b/i);
  if (reportTypeMatch) {
    result.reportType = reportTypeMatch[1].toUpperCase();
  }

  const fiscalYearMatch = text.match(/For the fiscal year ended[\s\S]{1,50}?(20\d{2})/i) || text.match(/FY\s*(20\d{2})/i);
  if (fiscalYearMatch) {
    result.fiscalYear = fiscalYearMatch[1];
  }

  const quarterMatch = text.match(/For the quarterly period ended[\s\S]{1,50}?([A-Z][a-z]+\s+\d{1,2},\s*20\d{2})/i);
  if (quarterMatch) {
    result.quarter = quarterMatch[1];
  }

  const filingDateMatch = text.match(/Filed[\s:]+([A-Z][a-z]+\s+\d{1,2},\s*20\d{2})/i) || text.match(/Date of Report[\s:]+([A-Z][a-z]+\s+\d{1,2},\s*20\d{2})/i);
  if (filingDateMatch) {
    result.filingDate = filingDateMatch[1];
  }

  const matchValue = (regex: RegExp) => {
    const match = text.match(regex);
    return match ? Number(match[1].replace(/,/g, "")) : undefined;
  };

  result.revenue = matchValue(/Total net sales\s+\$?\s*([\d,]+)/i);
  result.grossProfit = matchValue(/Gross margin\s+\$?\s*([\d,]+)/i);
  result.operatingIncome = matchValue(/Operating income\s+\$?\s*([\d,]+)/i);
  result.netIncome = matchValue(/Net income\s+\$?\s*([\d,]+)/i);
  
  result.cash = matchValue(/Cash and cash equivalents\s+\$?\s*([\d,]+)/i);
  result.totalAssets = matchValue(/Total assets\s+\$?\s*([\d,]+)/i);
  result.currentAssets = matchValue(/Total current assets\s+\$?\s*([\d,]+)/i);
  result.totalLiabilities = matchValue(/Total liabilities\s+\$?\s*([\d,]+)/i);
  result.currentLiabilities = matchValue(/Total current liabilities\s+\$?\s*([\d,]+)/i);
  result.shareholderEquity = matchValue(/Total shareholders[’'] equity\s+\$?\s*([\d,]+)/i);
  result.operatingCashFlow = matchValue(/Cash generated by operating activities\s+\$?\s*([\d,]+)/i);
  
  // Clean up undefined properties
  for (const key of Object.keys(result) as Array<keyof FinancialMetrics>) {
    if (result[key] === undefined) {
      delete result[key];
    }
  }

  return result;
}