import { FinancialMetrics } from "@/types/financial";

export function parseFinancialData(
  text: string
): FinancialMetrics {
  const result: FinancialMetrics = {};

  // Company
  const lines = text
    .split("\n")
    .map(line => line.trim())
    .filter(Boolean);

    if (lines.length > 0) {
        result.company = lines[0];
  }

  const matchValue = (regex: RegExp) => {
    const match = text.match(regex);
    return match ? Number(match[1].replace(/,/g, "")) : undefined;
  };

  result.revenue = matchValue(/Total net sales\s+\$?\s*([\d,]+)/i);
  result.grossProfit = matchValue(/Gross margin\s+\$?\s*([\d,]+)/i);
  result.operatingIncome = matchValue(/Operating income\s+\$?\s*([\d,]+)/i);
  result.netIncome = matchValue(/Net income\s+\$?\s*([\d,]+)/i);
  
  result.cash = matchValue(/Cash and cash equivalents\s+\$?\s*([\d,]+)/i);
  result.totalAssets = matchValue(/Total assets\s+\$?\s*([\d,]+)/i);
  result.currentAssets = matchValue(/Total current assets\s+\$?\s*([\d,]+)/i);
  result.totalLiabilities = matchValue(/Total liabilities\s+\$?\s*([\d,]+)/i);
  result.currentLiabilities = matchValue(/Total current liabilities\s+\$?\s*([\d,]+)/i);
  result.shareholderEquity = matchValue(/Total shareholders[’'] equity\s+\$?\s*([\d,]+)/i);
  result.operatingCashFlow = matchValue(/Cash generated by operating activities\s+\$?\s*([\d,]+)/i);
  
  // Clean up undefined properties
  for (const key of Object.keys(result) as Array<keyof FinancialMetrics>) {
    if (result[key] === undefined) {
      delete result[key];
    }
  }

  return result;
}